import type { TextOverlayAnimationKind, VersionTimeline } from "../types";

interface NativeTemplateBeat {
  text: string;
  color?: string;
  fontFamily?: "sans" | "serif" | "mono";
  fontSize?: number;
  fontStyle?: "normal" | "italic";
  motion?: TextOverlayAnimationKind;
  y?: number;
}

const createNativeThreeBeatBlueprint = (
  templateId: string,
  beats: readonly [NativeTemplateBeat, NativeTemplateBeat, NativeTemplateBeat],
): VersionTimeline => ({
  aspect: "reel_9_16",
  clips: beats.map((_, index) => ({
    id: `${templateId}-scene-${String(index + 1).padStart(2, "0")}`,
    assetId: `${templateId}-image-${String(index + 1).padStart(2, "0")}`,
    kind: "image" as const,
    startFrame: index * 90,
    endFrame: (index + 1) * 90,
    trimStartFrame: 0,
    trimEndFrame: 90,
    volume: 1,
  })),
  textOverlays: beats.map((beat, index) => ({
    id: `${templateId}-title-${String(index + 1).padStart(2, "0")}`,
    text: beat.text,
    startFrame: index * 90 + 8,
    endFrame: (index + 1) * 90 - 7,
    x: 50,
    y: beat.y ?? 52,
    fontSize: beat.fontSize ?? 68,
    color: beat.color ?? "#f2ede3",
    fontFamily: beat.fontFamily ?? "sans",
    fontWeight: 700,
    fontStyle: beat.fontStyle ?? "normal",
    textAlign: "center" as const,
    stylePreset: "classic" as const,
    createdaleyTexture: "plain" as const,
    animation: {
      in: beat.motion ?? "rise",
      out: "fade" as const,
      durationFrames: beat.motion === "word-reveal" ? 18 : 12,
    },
  })),
  audioTracks: [],
  transitions: [
    {
      id: `${templateId}-transition-01`,
      kind: "wipe",
      durationInFrames: 12,
      fromClipId: `${templateId}-scene-01`,
      toClipId: `${templateId}-scene-02`,
      direction: "left",
      easing: "ease-out",
    },
    {
      id: `${templateId}-transition-02`,
      kind: "slide",
      durationInFrames: 12,
      fromClipId: `${templateId}-scene-02`,
      toClipId: `${templateId}-scene-03`,
      direction: "up",
      easing: "ease-out",
    },
  ],
});

/**
 * Editor-native starter projects. The ids in these blueprints are semantic
 * placeholders; instantiateTemplateBlueprint replaces them with session ids.
 */
export const FLAGSHIP_TEMPLATE_BLUEPRINTS = {
  "editorial-explainer": {
    aspect: "reel_9_16",
    clips: [
      {
        id: "editorial-explainer-scene-01",
        assetId: "editorial-explainer-image-01",
        kind: "image",
        startFrame: 0,
        endFrame: 105,
        trimStartFrame: 0,
        trimEndFrame: 105,
        volume: 1,
      },
      {
        id: "editorial-explainer-scene-02",
        assetId: "editorial-explainer-image-02",
        kind: "image",
        startFrame: 105,
        endFrame: 210,
        trimStartFrame: 0,
        trimEndFrame: 105,
        volume: 1,
      },
      {
        id: "editorial-explainer-scene-03",
        assetId: "editorial-explainer-image-03",
        kind: "image",
        startFrame: 210,
        endFrame: 315,
        trimStartFrame: 0,
        trimEndFrame: 105,
        volume: 1,
      },
    ],
    textOverlays: [
      {
        id: "editorial-explainer-headline",
        text: "THE SIGNAL\nBEHIND THE STORY",
        startFrame: 8,
        endFrame: 102,
        x: 50,
        y: 42,
        fontSize: 66,
        color: "#f2ede3",
        fontFamily: "sans",
        fontWeight: 700,
        fontStyle: "normal",
        stylePreset: "classic",
        createdaleyTexture: "plain",
        animation: { in: "word-reveal", out: "fade", durationFrames: 16 },
      },
      {
        id: "editorial-explainer-context",
        text: "Three moments that changed how we read the room.",
        startFrame: 112,
        endFrame: 207,
        x: 50,
        y: 74,
        fontSize: 44,
        color: "#f2ede3",
        fontFamily: "serif",
        fontWeight: 400,
        fontStyle: "italic",
        stylePreset: "classic",
        createdaleyTexture: "plain",
        animation: { in: "rise", out: "fade", durationFrames: 16 },
      },
      {
        id: "editorial-explainer-close",
        text: "LOOK CLOSER.\nTHE PATTERN IS ALREADY THERE.",
        startFrame: 220,
        endFrame: 307,
        x: 50,
        y: 70,
        fontSize: 48,
        color: "#ff4f1f",
        fontFamily: "sans",
        fontWeight: 700,
        fontStyle: "normal",
        stylePreset: "classic",
        createdaleyTexture: "plain",
        animation: { in: "punch", durationFrames: 12 },
      },
    ],
    audioTracks: [
      {
        id: "editorial-explainer-bed",
        assetId: "editorial-explainer-audio-bed",
        startFrame: 0,
        endFrame: 315,
        trimStartFrame: 0,
        trimEndFrame: 315,
        volume: 0.62,
        fadeInFrames: 18,
        fadeOutFrames: 24,
        muted: false,
      },
    ],
    transitions: [
      {
        id: "editorial-explainer-transition-01",
        kind: "fade",
        durationInFrames: 15,
        fromClipId: "editorial-explainer-scene-01",
        toClipId: "editorial-explainer-scene-02",
        easing: "ease-out",
      },
      {
        id: "editorial-explainer-transition-02",
        kind: "slide",
        durationInFrames: 15,
        fromClipId: "editorial-explainer-scene-02",
        toClipId: "editorial-explainer-scene-03",
        direction: "left",
        easing: "ease-out",
      },
    ],
  },
  "product-reveal": {
    aspect: "reel_9_16",
    clips: [
      {
        id: "product-reveal-scene-01",
        assetId: "product-reveal-image-01",
        kind: "image",
        startFrame: 0,
        endFrame: 90,
        trimStartFrame: 0,
        trimEndFrame: 90,
        volume: 1,
      },
      {
        id: "product-reveal-scene-02",
        assetId: "product-reveal-image-02",
        kind: "image",
        startFrame: 90,
        endFrame: 180,
        trimStartFrame: 0,
        trimEndFrame: 90,
        volume: 1,
      },
      {
        id: "product-reveal-scene-03",
        assetId: "product-reveal-image-03",
        kind: "image",
        startFrame: 180,
        endFrame: 285,
        trimStartFrame: 0,
        trimEndFrame: 105,
        volume: 1,
      },
    ],
    textOverlays: [
      {
        id: "product-reveal-kicker",
        text: "INTRODUCING\nMOMENTUM",
        startFrame: 12,
        endFrame: 84,
        x: 50,
        y: 28,
        fontSize: 48,
        color: "#ff4f1f",
        fontFamily: "mono",
        fontWeight: 700,
        fontStyle: "normal",
        stylePreset: "classic",
        createdaleyTexture: "plain",
        animation: { in: "word-reveal", out: "fade", durationFrames: 20 },
      },
      {
        id: "product-reveal-name",
        text: "A SMALLER\nWAY FORWARD",
        startFrame: 18,
        endFrame: 86,
        x: 50,
        y: 46,
        fontSize: 72,
        color: "#f2ede3",
        fontFamily: "sans",
        fontWeight: 700,
        fontStyle: "normal",
        stylePreset: "classic",
        createdaleyTexture: "plain",
        animation: { in: "punch", out: "fade", durationFrames: 12 },
      },
      {
        id: "product-reveal-benefit",
        text: "QUIETLY POWERFUL.\nDELIGHTFULLY SIMPLE.",
        startFrame: 102,
        endFrame: 174,
        x: 50,
        y: 73,
        fontSize: 42,
        color: "#f2ede3",
        fontFamily: "serif",
        fontWeight: 400,
        fontStyle: "italic",
        stylePreset: "classic",
        createdaleyTexture: "plain",
        animation: { in: "rise", out: "fade", durationFrames: 16 },
      },
      {
        id: "product-reveal-cta",
        text: "MAKE ROOM FOR MORE.",
        startFrame: 198,
        endFrame: 277,
        x: 50,
        y: 80,
        fontSize: 48,
        color: "#ff4f1f",
        fontFamily: "sans",
        fontWeight: 700,
        fontStyle: "normal",
        stylePreset: "classic",
        createdaleyTexture: "plain",
        animation: { in: "slide-left", durationFrames: 14 },
      },
    ],
    audioTracks: [
      {
        id: "product-reveal-bed",
        assetId: "product-reveal-audio-bed",
        startFrame: 0,
        endFrame: 285,
        trimStartFrame: 0,
        trimEndFrame: 285,
        volume: 0.55,
        fadeInFrames: 12,
        fadeOutFrames: 18,
        muted: false,
      },
    ],
    transitions: [
      {
        id: "product-reveal-transition-01",
        kind: "wipe",
        durationInFrames: 12,
        fromClipId: "product-reveal-scene-01",
        toClipId: "product-reveal-scene-02",
        direction: "up",
        easing: "ease-out",
      },
      {
        id: "product-reveal-transition-02",
        kind: "fade",
        durationInFrames: 18,
        fromClipId: "product-reveal-scene-02",
        toClipId: "product-reveal-scene-03",
        easing: "ease-out",
      },
    ],
  },
  "social-promo": {
    aspect: "reel_9_16",
    clips: [
      {
        id: "social-promo-scene-01",
        assetId: "social-promo-image-01",
        kind: "image",
        startFrame: 0,
        endFrame: 75,
        trimStartFrame: 0,
        trimEndFrame: 75,
        volume: 1,
      },
      {
        id: "social-promo-scene-02",
        assetId: "social-promo-image-02",
        kind: "image",
        startFrame: 75,
        endFrame: 150,
        trimStartFrame: 0,
        trimEndFrame: 75,
        volume: 1,
      },
      {
        id: "social-promo-scene-03",
        assetId: "social-promo-image-03",
        kind: "image",
        startFrame: 150,
        endFrame: 240,
        trimStartFrame: 0,
        trimEndFrame: 90,
        volume: 1,
      },
    ],
    textOverlays: [
      {
        id: "social-promo-hook",
        text: "STOP SCROLLING.\nSTART MAKING.",
        startFrame: 7,
        endFrame: 71,
        x: 50,
        y: 42,
        fontSize: 68,
        color: "#f2ede3",
        fontFamily: "sans",
        fontWeight: 700,
        fontStyle: "normal",
        stylePreset: "classic",
        createdaleyTexture: "plain",
        animation: { in: "punch", out: "fade", durationFrames: 10 },
      },
      {
        id: "social-promo-proof",
        text: "ONE IDEA.\nTHREE SECONDS.\nA THOUSAND WAYS IN.",
        startFrame: 82,
        endFrame: 145,
        x: 50,
        y: 66,
        fontSize: 46,
        color: "#ff4f1f",
        fontFamily: "mono",
        fontWeight: 700,
        fontStyle: "normal",
        stylePreset: "classic",
        createdaleyTexture: "plain",
        animation: { in: "word-reveal", out: "fade", durationFrames: 18 },
      },
      {
        id: "social-promo-cta",
        text: "YOUR NEXT CUT\nSTARTS HERE →",
        startFrame: 160,
        endFrame: 229,
        x: 50,
        y: 76,
        fontSize: 52,
        color: "#f2ede3",
        fontFamily: "sans",
        fontWeight: 700,
        fontStyle: "normal",
        stylePreset: "classic",
        createdaleyTexture: "plain",
        animation: { in: "rise", durationFrames: 14 },
      },
    ],
    audioTracks: [
      {
        id: "social-promo-bed",
        assetId: "social-promo-audio-bed",
        startFrame: 0,
        endFrame: 240,
        trimStartFrame: 0,
        trimEndFrame: 240,
        volume: 0.68,
        fadeInFrames: 9,
        fadeOutFrames: 15,
        muted: false,
      },
    ],
    transitions: [
      {
        id: "social-promo-transition-01",
        kind: "slide",
        durationInFrames: 10,
        fromClipId: "social-promo-scene-01",
        toClipId: "social-promo-scene-02",
        direction: "right",
        easing: "ease-in",
      },
      {
        id: "social-promo-transition-02",
        kind: "wipe",
        durationInFrames: 10,
        fromClipId: "social-promo-scene-02",
        toClipId: "social-promo-scene-03",
        direction: "left",
        easing: "ease-out",
      },
    ],
  },
  "documentary-cut": createNativeThreeBeatBlueprint("documentary-cut", [
    {
      text: "THE NIGHT\nTHE WALL OPENED",
      color: "#f2ede3",
      fontFamily: "serif",
      fontSize: 72,
      motion: "word-reveal",
      y: 42,
    },
    {
      text: "ONE ANNOUNCEMENT\nCHANGED THE BORDER",
      color: "#ffb347",
      fontSize: 62,
      motion: "slide-left",
      y: 55,
    },
    {
      text: "BY MIDNIGHT,\nHISTORY WAS MOVING.",
      color: "#f2ede3",
      fontFamily: "serif",
      fontSize: 66,
      fontStyle: "italic",
      motion: "rise",
      y: 68,
    },
  ]),
  "data-pulse": createNativeThreeBeatBlueprint("data-pulse", [
    {
      text: "95%\nSTILL UNEXPLORED",
      color: "#ff6b35",
      fontSize: 82,
      motion: "punch",
      y: 44,
    },
    {
      text: "3 SECONDS\nTO EARN ATTENTION",
      color: "#f2ede3",
      fontSize: 72,
      motion: "rise",
      y: 52,
    },
    {
      text: "1 TIMELINE\nEVERYTHING EDITABLE",
      color: "#ffb347",
      fontSize: 68,
      motion: "word-reveal",
      y: 62,
    },
  ]),
  "quote-reel": createNativeThreeBeatBlueprint("quote-reel", [
    {
      text: "“WE DIDN’T JUST\nREDRAW THE MAP.”",
      color: "#f2ede3",
      fontFamily: "serif",
      fontSize: 62,
      fontStyle: "italic",
      motion: "word-reveal",
      y: 42,
    },
    {
      text: "“WE REDREW\nWHO BELONGS.”",
      color: "#ffb347",
      fontFamily: "serif",
      fontSize: 70,
      fontStyle: "italic",
      motion: "punch",
      y: 54,
    },
    {
      text: "THE FRAME\nMAKES THE ARGUMENT.",
      color: "#f2ede3",
      fontSize: 68,
      motion: "rise",
      y: 68,
    },
  ]),
} satisfies Record<string, VersionTimeline>;

export type FlagshipTemplateId = keyof typeof FLAGSHIP_TEMPLATE_BLUEPRINTS;

/**
 * Clone a blueprint into a fresh editable timeline and inject caller-owned ids.
 * Transition endpoints are remapped, so blueprints never leak placeholder ids.
 */
export const instantiateTemplateBlueprint = (
  blueprint: VersionTimeline,
  createId: () => string,
): VersionTimeline => {
  const clipIds = new Map(blueprint.clips.map((clip) => [clip.id, createId()]));
  const textIds = new Map(
    blueprint.textOverlays.map((overlay) => [overlay.id, createId()]),
  );
  const audioIds = new Map(
    blueprint.audioTracks.map((track) => [track.id, createId()]),
  );

  return {
    aspect: blueprint.aspect,
    clips: blueprint.clips.map((clip) => ({
      ...clip,
      id: clipIds.get(clip.id) ?? clip.id,
    })),
    textOverlays: blueprint.textOverlays.map((overlay) => ({
      ...overlay,
      id: textIds.get(overlay.id) ?? overlay.id,
      ...(overlay.animation ? { animation: { ...overlay.animation } } : {}),
    })),
    audioTracks: blueprint.audioTracks.map((track) => ({
      ...track,
      id: audioIds.get(track.id) ?? track.id,
    })),
    transitions: blueprint.transitions.map((transition) => ({
      ...transition,
      id: createId(),
      fromClipId: clipIds.get(transition.fromClipId) ?? transition.fromClipId,
      toClipId: clipIds.get(transition.toClipId) ?? transition.toClipId,
    })),
  };
};

export const instantiateFlagshipTemplate = (
  templateId: FlagshipTemplateId,
  createId: () => string,
): VersionTimeline =>
  instantiateTemplateBlueprint(FLAGSHIP_TEMPLATE_BLUEPRINTS[templateId], createId);
